### ISSUE TITLE
Improve docs for customFields at /checkouts/{checkoutId}/billing-address

### ISSUE THREAD

**Issue by zeekrey** [bigcommerce/dev-docs#1013]
**Hey there,**

the docs or schema at https://developer.bigcommerce.com/api-reference/store-management/checkouts/checkout-billing-address/checkoutsbillingaddressbycheckoutidpost says that the field for custom fields is called "custom_fields". When using "custom_fields" you'll get a HTTP 500 response. It only works if the field is called "customFields".

Please improve the docs so that is shows the right field name (customFields). 

Cheers
**Christian**

**Comment by uwikaiddi** [comment]
Hi @zeekrey! Thanks for bringing our attention to this. 
We've created a ticket to address the issue.

**Comment by traci707** [comment]
@zeekrey This issue has been resolved. However, the link referenced above is incorrect.  It should be this link.
https://developer.bigcommerce.com/api-reference/storefront/checkouts/checkout-billing-address/checkoutsbillingaddressbycheckoutidandaddressidput
