### ISSUE TITLE
Example Request Payload for Storefront API - "Add Line Items to Cart" are incorrect - requires snake_case not camelCase

### ISSUE THREAD

**Issue by Mikhail-MM** [bigcommerce/dev-docs#1129]
This example payload in the BigCommerce API Reference for the Storefront Carts API is incorrect:

Screenshot
https://www.screencast.com/t/SFferOPpij

This should all be `snake_case` instead of `camelCase`: 

Correct:
```
option_selections: [{ option_id, option_value}]
```

Incorrect:
```
optionSelections: [{ optionId, optionValue }]
```

**Comment by uwikaiddi** [comment]
Thank you for pointing this out to us, @Mikhail-MM! We've opened a ticket to address this.
This update should be made within the next week.
