### ISSUE TITLE
App Quick Start guide links to codesandbox.io without listing it in prerequisites

### ISSUE THREAD

**Issue by tipleyg** [bigcommerce/dev-docs#1277]
App Quick Start guide links to codesandbox.io and presumes that one is using it without listing it in prerequisites. It's also unclear when the guide is using "sandbox" to mean "codesandbox.io" or the BigCommerce store which is also referred to as a sandbox

https://developer.bigcommerce.com/api-docs/apps/quick-start

> After registering the app, enter the app’s credentials and auth callback into your sandbox’s environment variables (codesandbox.io).

**Comment by slsriehl** [comment]
@tipleyg We've updated our sample app documentation to focus on the [Node / React / Next.js sample app](https://github.com/bigcommerce/sample-app-nodejs).  The [App Quick Start guide](https://developer.bigcommerce.com/api-docs/apps/quick-start) reflects these changes, and references to codesandbox.io no longer appear.
