### ISSUE TITLE
Following documentation to build a Next.JS app downloads incorrect package.

### ISSUE THREAD

**Issue by ZacharySeebeck2020** [bigcommerce/dev-docs#1383]
Following the instructions on your 'Build A Next.JS Sample App' tutorial located [here](https://developer.bigcommerce.com/api-docs/apps/tutorials/sample-app-nextjs/step-2-connect), in step 2 it asks for you to install `node-bigcommerce`.

Doing so, incorrectly, gives you [this](https://www.npmjs.com/package/node-bigcommerce) package. Which in theory would be fine, minus the fact that going down a few steps and running your code with this package will provide the error of `bigcommerceSigned.verifyJWT is not a function`. 

The verifyJWT function was recently added in the bigcommerce/node-bigcommerce repo. 

Currently, to get around this issue, I just installed the BigCommerce package directly from the repo with `npm install https://github.com/bigcommerce/node-bigcommerce`

I'm not 100% sure if this is something on my end, but once doing that, everything works as intended.

**Comment by slsriehl** [comment]
Hi @ZacharySeebeck2020 -- thanks for reporting.  You are doing the right thing at the moment.  I've opened a ticket to update the documentation.

**Comment by MikeAplazo** [comment]
I still have the same issue

**Comment by slsriehl** [comment]
@ZacharySeebeck2020 We updated the tutorial in the referenced PRs. Thanks again for reporting this. 

cc @MikeAplazo
