### ISSUE TITLE
Inconsistent parameters in first OAuth get request

### ISSUE THREAD

**Issue by Sjord** [bigcommerce/dev-docs#1601]
[dev-docs/apps-05-oauth.md](https://github.com/bigcommerce/dev-docs/blob/master/docs/api-docs/apps/guide/apps-05-oauth.md) describes the parameters to the first GET request in two places, and there are inconsistent. I would expect the parameters listed to be identical, but they are different.

Under [OAuth summary](https://github.com/bigcommerce/dev-docs/blob/master/docs/api-docs/apps/guide/apps-05-oauth.md#oauth-summary), step 1:

> [GET](https://github.com/bigcommerce/dev-docs/blob/master/docs/api-docs/apps/guide/apps-05-oauth.md#receiving-the-get-request) request from BigCommerce to your app (triggered by merchant clicking Install) containing:
> * code
> * client_id
> * client_secret
> * scopes

Under [Receiving the GET request](https://github.com/bigcommerce/dev-docs/blob/master/docs/api-docs/apps/guide/apps-05-oauth.md#receiving-the-get-request):

> ```http
> GET /auth?code=qr6h3thvbvag2ffq&scope=store_v2_orders&context=stores/g5cd38 HTTP/1.1
> ```
> 
> | Parameter | Description |
> |-|-|
> | `code` | Temporary code to exchange for a permanent `access_token`. |
> | `scope` | List of scopes authorized by the user. |
> | `context` | The `store_hash` in the form of `stores/{{STORE_HASH}}`; required in API requests.|
>

**Comment by slsriehl** [comment]
@Sjord You were absolutely correct. We updated the doc in the referenced PRs. Thanks for reporting this.
