### ISSUE TITLE
No documentation for `{{each}}` in the Handlebars Helpers Reference

### ISSUE THREAD

**Issue by Christopher-Hayes** [bigcommerce/dev-docs#1644]
`{{each}}` is used in examples of the [Handlebars Helpers Reference](https://developer.bigcommerce.com/stencil-docs/ZG9jOjIyMDcxOA-handlebars-helpers-reference); however, it's not actually documented anywhere in the document.

Somewhat related, the number of helpers for loops is a little overwhelming, could be useful to have a somewhere that helps users choose which one to use. (There's `each`, `eachIndex`, `forEach`, `forOwn`, `forIn`, and `iterate` from what I could see)

**Comment by slsriehl** [comment]
@Christopher-Hayes Thanks for raising this. `{{each}}` uses the standard helper. We'll update the docs.

**Comment by slsriehl** [comment]
Published.
