### ISSUE TITLE
Running `grunt textlint` causes GitHub rate limits

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/dev-docs#1693]
As advised in the contributing guide, running `grunt textlint` causes Github API Rate Limits to be applied to your account, the command ultimately fails. This looks like it relates to the no-dead-link check.

```
.../dev-docs/docs/stencil-docs/storefront-customization/using-front-matter.md
  94:129  error  https://github.com/bigcommerce/cornerstone/blob/master/templates/pages/product.html is dead. (429 too many requests)  no-dead-link
```

**Comment by slsriehl** [comment]
Hi @AndrewBarber -- We're no longer actively maintaining the grunt linter and have no plans to resume. We have some improvements coming. I'm keeping this comment open to ensure we communicate the new default linting procedure.
