### ISSUE TITLE
Feedback for “Overview”

### ISSUE THREAD

**Issue by arnold-overby-SIM** [bigcommerce/dev-docs#1806]
Links from the Overview tiles on https://developer.bigcommerce.com/api-docs/overview result in 404-Page not found errors.
Examples:

- https://developer.bigcommerce.com/api-docs/building-apps/apps-quick-start
- https://developer.bigcommerce.com/api-docs/multi-storefront-implementations/msf-api-guide
- https://developer.bigcommerce.com/api-docs/building-channels/guide/building-channel-apps

**Comment by slsriehl** [comment]
thanks, @arnold-overby-SIM! The tiles all currently 200. We appreciate your contribution to our docs quality.
