### ISSUE TITLE
Feedback for “Installing Custom Checkouts”

### ISSUE THREAD

**Issue by Farhan71** [bigcommerce/dev-docs#1813]
This documentation page shows 404:page not found error. Plz repair that page.

**Comment by slsriehl** [comment]
@Farhan71 Thanks for contributing to our docs. The bulk of our 404 errors are currently resolved, and Installing Custom Checkouts is currently available at https://developer.bigcommerce.com/stencil-docs/customizing-checkout/installing-custom-checkouts.
