### ISSUE TITLE
What’s missing in your documentation

### ISSUE THREAD

**Issue by cliffvick** [bigcommerce/dev-docs#1818]
If there were just a short section that described how it all fits together - how to think about all of it: stencil, handlebars, the console, apps, etc. etc. etc.

The most difficult thing that I have found about trying to learn from your documentation is that, usually, there is some idea or concept that is referenced that I have no idea what it is or how it works.

Draw me a picture of how to think about everything and how each piece relates to the other pieces. So much of my time is spent wading through your documentation trying to find anything that will help me solve whatever problem I am trying to solve. Once I, finally, have a good mental model of something, then it’s very easy to find what I am looking for in your documentation.  However, during the process when I’m trying to learn how everything works while simultaneously trying to implement my client’s changes, I find it almost impossible sometime to find what I need, and the reason is that I don’t have a good mental model of things.

If you could add a section in your documentation that describes the concepts and how they all relate to one another, some illustrations, say, of how a page gets build from all of the various little pieces, it would make your documentation so much more ingestible and understandable from the point of view of someone like me: a developer who knew absolutely nothing about Big Commerce, Stencil, how themes works, etc. etc.  It’s been an awful uphill climb, and, after months of trying to get that understanding, I am *just* beginning to understand how it all fits together and how I can be most valuable to my client.

**Comment by slsriehl** [comment]
Thanks for commenting, @cliffvick. Although we haven't responded until now, your feedback and similar sentiments from others have informed many of the changes we've made in the past several months, to make getting started more accessible. We have more enablement content in the works that we hope will continue building a coherent, accessible model of how our developer products work together.

We appreciate your contribution to this conversation and your work in the BigCommerce space.
