### ISSUE TITLE
Feedback for “Promotions Single”

### ISSUE THREAD

**Issue by 5874** [bigcommerce/dev-docs#1822]
I think this page is broken.
There is no detail about what is needed in the body to update.
The previous API listed the properties.

**Comment by bc-traciporter** [comment]
Are you referring to this page, https://developer.bigcommerce.com/promotions/rest-management/coupon-codes-single ?

**Comment by slsriehl** [comment]
@5874 Thanks for contributing to our docs. We've worked through many of our recent issues with request body properties not rendering, and the [Create a promotion](https://developer.bigcommerce.com/promotions/rest-management/promotions-single) endpoint documentation now contains a request body schema. 

If this answer doesn't address your original issue, please open a fresh issue and include the URL of the documentation you're referencing.
