### ISSUE TITLE
Feedback for “Custom Templates”

### ISSUE THREAD

**Issue by cliffvick** [bigcommerce/dev-docs#1823]
“ After editing your .stencil or config.stencil.json files (if you are using Stencil V3.1 release or later), you must restart the Stencil app to view your changes locally. To restart stencil, type stencil start at a command prompt, and append the appropriate switches for your workflow, for example: stencil start -e -n.”

Looking in the `stencil start` documentation (https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands#stencil-init), I cannot find anything that explains what the `-e` option to stencil start does.

**Comment by slsriehl** [comment]
See the table under https://developer.bigcommerce.com/docs/storefront/stencil/cli/options-and-commands#stencil-download.
