### ISSUE TITLE
Can we update only a few properties on a product?

### ISSUE THREAD

**Issue by catcode02** [bigcommerce/dev-docs#1834]
Hello -

We would like to update only a select attirbutes via API. Is that possible to do with the new api? If not, when will that be available ?

Thank you!
CJ

**Comment by slsriehl** [comment]
Hi @catcode02 -- it is possible to update only some attributes of a product using the Catalog V3 API. https://developer.bigcommerce.com/docs/rest-catalog/products#update-products-batch

For more support, check out our Dev Community Slack or Discord channels; see https://developer.bigcommerce.com/community to get started.
