### ISSUE TITLE
Feedback for “Listening for Events”

### ISSUE THREAD

**Issue by obrien-k** [bigcommerce/dev-docs#1837]
The "Webhooks Overview" link is dead: https://developer.bigcommerce.com/api-docs/getting-started/webhooks/setting-up-webhooks
[Resources > Related Articles](https://developer.bigcommerce.com/api-docs/apps/guide/events#related-articles)

Should be: https://developer.bigcommerce.com/api-docs/store-management/webhooks/about-webhooks

**Comment by slsriehl** [comment]
Thanks @obrien-k! These links now reflect the current information architecture. 

We appreciate your help making our developer resources better.
