### ISSUE TITLE
Feedback for “Embedded Checkout”

### ISSUE THREAD

**Issue by Ash-Matter** [bigcommerce/dev-docs#1852]
Can you please expand on the `embedCheckout` method and show where/how you're expecting the function to be imported into the code, covering all possible versions.
Thanks

**Comment by slsriehl** [comment]
Hi @Ash-Matter -- we appreciate your work to improve our documentation and enablement content. At this time, we do not have plans to produce new documentation about embedded checkout. If you'd like to raise this issue again or make further requests, you can open an issue or PR in our new consolidated repository at https://github.com/bigcommerce/docs.
