### ISSUE TITLE
Feedback for “Add to Cart URLs”

### ISSUE THREAD

**Issue by cplabsafety** [bigcommerce/dev-docs#1875]
These codes don't work on our site. I've tried several variations of the url strings provided, and none of these results in this sku being added to cart.

https://www.calpaclab.com/cart.php?action=add&sku=CPLS-LANYARD
https://www.calpaclab.com/cart.php?action=buy&sku=EF-4-38
https://www.calpaclab.com/cart.php?action=buy&sku=CPLS-LANYARD&couponcode=WELCOME10

**Comment by slsriehl** [comment]
Hi @cplabsafety -- for more assistance with this and other developer questions, consider joining our Dev Community on Slack or Discord. See https://developer.bigcommerce.com/community for more information.
