### ISSUE TITLE
Feedback for “Checkout SDK”

### ISSUE THREAD

**Issue by JamesLee-BC** [bigcommerce/dev-docs#1880]
https://developer.bigcommerce.com/stencil-docs/customizing-checkout/checkout-sdk#required-payment-method-initialization-options

Link results in 404

<img width="876" alt="Screenshot 2023-04-13 at 9 16 29 AM" src="https://user-images.githubusercontent.com/78035635/231788037-1be7ccb3-c999-4d7a-b7a5-b41e4119c555.png">

**Comment by slsriehl** [comment]
link no longer 404s
