### ISSUE TITLE
Feedback for “Catalog Overview”

### ISSUE THREAD

**Issue by atensoftware** [bigcommerce/dev-docs#1915]
Key information regarding product->variant inheritance and updating products is missing from this documentation, and is also not mentioned in the API reference.

There is just an oblique mention that variants, "Can have their own price, weight, dimensions, image, etc. - or they can inherit these values from the product if you have not specified them."

What value should variant_price (or other variant fields) be set to in order to make it inherit the price from the product?  My understanding is that if it is null or left out of the API call, then it is not changed.

Does updating price on the product automatically override the variant_prices?  If not, which prices get overridden?

I'm hoping you can add this information to the documentation. Thank you!

**Comment by slsriehl** [comment]
Hi @atensoftware -- we do have improvements to this doc in the works. Thanks for weighing in!
