### ISSUE TITLE
Feedback for “Webhook Events”

### ISSUE THREAD

**Issue by ganeshlohar10** [bigcommerce/dev-docs#1920]
hash : The payload data JSON encoded then passed through SH1 encryption.

this is written in this doc 
https://developer.bigcommerce.com/api-docs/store-management/webhooks/webhook-events#callback-structure

tho when i'm trying to generate hash using app secret
not get generated correctly

please provide more information on how exactly the hash should be generated

**Comment by slsriehl** [comment]
@ganeshlohar10 I believe the hash in question comes from BigCommerce as part of the webhooks payload. It is not something that you need to assemble. As for information about validating the hash, we've created ticket [DEVDOCS-5017].
