### ISSUE TITLE
Feedback for “BigCommerce Apps Quick Start”

### ISSUE THREAD

**Issue by bensinclair-leith** [bigcommerce/dev-docs#1921]
You're missing some steps in the quick start:

You mention needing to add `CLIENT_ID `and `CLIENT_SECRET`, which both have placeholders in the .env.sample file, but the app also requires `STORE_HASH `and `ACCESS_TOKEN `to be set.

You need to already have a database prepared, and then run `npm db:setup`  to initialise it before you can run the server locally.

**Comment by slsriehl** [comment]
Thanks for this feedback, @bensinclair-leith. We've created [DEVDOCS-5106] to look into revising the docs.

**Comment by slsriehl** [comment]
This work was completed in 
* #2028
