### ISSUE TITLE
“Using Front Matter”: Remove statement that you can't use front matter in custom templates

### ISSUE THREAD

**Issue by CNanninga** [bigcommerce/dev-docs#1925]
It's outdated to list `templates/pages/custom/` as one of the directories where YAML front matter cannot be used.  The sentence "Injecting objects in the front matter of `templates/pages/page.html` will make the objects available to custom templates." should also be removed because it refers to the same previous restriction.

**Comment by slsriehl** [comment]
Thanks, @CNanninga. We've created [DEVDOCS-5105] to revisit this question and clarify the docs.
