### ISSUE TITLE
Feedback for “Introduction to Headless Commerce”

### ISSUE THREAD

**Issue by don-esteban** [bigcommerce/dev-docs#1938]
Hi, this is probably a more sales oriented question. I'm uncertain if this is the right place. But I could not easily find an answer on your site.

Do all plans offer Headless Ecommerce?

We have a successful Gatsby/React Site and would like to add cart/checkout/payment functionality. Does Pro Plan offer API access?

Thanks,
Stefan

**Comment by becomevocal** [comment]
@don-esteban it's possible you found the answer to this question by now, but yes! The pro plan includes, at the time of writing this, up to 8 storefronts that can be either our hosted storefront or headless storefronts like your Gatsby site. *All* plans currently support headless.
