### ISSUE TITLE
Feedback for “Adding Buy Online, Pick up in Store Features to the Storefront”

### ISSUE THREAD

**Issue by oshipper** [bigcommerce/dev-docs#1974]
Why would you screenshot other companies NOT using BigCommerce when showing the front end "experience" on a supposedly ready for prime time bigcommerce BOPIS feature? 

Is this yet another vaporware announcement? If not provide a working demo with code and a bigcommerce customer actually using it. 

Until then this announcement is obviously intended for investors and not real world use.

**Comment by slsriehl** [comment]
Hi @oshipper. Based on this feedback, we've created [DEVDOCS-5104] to improve some of our content.

In the meantime, what your storefront code looks like will depend on whether you're building for a Stencil storefront or a headless one. You can use the GraphQL Storefront API to fetch inventory per location; see https://developer.bigcommerce.com/buy-online-pick-up-in-store/graphql-storefront/inventory-queries#fetch-inventory-for-variants-at-each-location. You can also use the REST Management API; see https://developer.bigcommerce.com/buy-online-pick-up-in-store/rest-management/inventory/items#get-inventory-at-locations.

If you're developing for a Stencil storefront, you can add a custom GraphQL Storefront API query to the front matter of a page template, which expands the data available to the template. For more information, see https://developer.bigcommerce.com/stencil-docs/reference-docs/front-matter-reference#graphql-attributes.

Thank you for your contribution. For support developing for BigCommerce, consider joining our [developer community on Slack or Discord](https://developer.bigcommerce.com/community).

**Comment by oshipper** [comment]
All I'm asking is that you actually provide a working example of BOPIS on Stencil instead of screenshots of Apple's store which is clearly not on BigCommerce.

Should you really announce you support a function if you cannot create an demo example using these "best practices" you cite from non BigCommerce stores?

"BigCommerce Advances Enterprise Platform with Launch of BOPIS to Drive Merchant Growth" is a wildly different statement compared to "Go build from scratch, here's an api doc."

Furthermore your marketing team says this:  “With this latest evolution of our omnichannel offering, BigCommerce **makes it easy for merchants to offer BOPIS** to their customers and coordinate orders and inventories across branded sites, social, search, marketplace and brick-and-mortar channels” 

Where is this Easy to implement BOPIS mentioned in the press release?

**Comment by slsriehl** [comment]
DEVDOCS-5104 is complete. Thank you for your feedback. 

More enablement content and reference implementations are in ideation in 2024. 

Please open any new issues in https://github.com/bigcommerce/docs/issues.
