### ISSUE TITLE
Top level documentation node added on every click in the tree

### ISSUE THREAD

**Issue by mmesdag** [bigcommerce/dev-docs#1983]
Every time I click any node in the documentation tree, a new top level item for 'GraphQL Storefront API' is added. Causes the UI to jump and makes it hard to get to the documentation I actually want

![2023-06-20_16-17-39 (1)](https://github.com/bigcommerce/dev-docs/assets/110251612/95b14abd-3eb6-4b7b-a14b-8e49f619a76b)

**Comment by slsriehl** [comment]
This bug has been resolved. Thanks for reporting!
