### ISSUE TITLE
Custom Bigcommerce App With form fields | CRUD Opration

### ISSUE THREAD

**Issue by Kaushik-d44** [bigcommerce/dev-docs#2043]
Hi All, I have created a sample Bigcommerce APP with the form fields. I want to insert and display app fields data. 
Anyone have an idea regarding this?

Thanks in Advance

**Comment by slsriehl** [comment]
Hi @Kaushik-d44! Thanks for reaching out to the BigCommerce DX team. For this kind of help, we currently recommend that you join our Dev Slack or Discord. Learn more and sign up at https://developer.bigcommerce.com/community.
