### ISSUE TITLE
Feedback for “Integration Design”

### ISSUE THREAD

**Issue by Tecktron** [bigcommerce/dev-docs#2103]
This statement:

> read operations are faster and have lower error rates.

**is a 100% a LIE and is absolutely FALSE.** 
Your API is a _MASSIVE_ hunk of shit and fails (with 500s) for us _ALL_ the time, _ESPECIALLY_ GET requests (and we have so many fail logs to back this up). 

Also you should add in information about your constant SSL errors as your shitty infrastructure gives us tons of those as well.

**Comment by Tecktron** [comment]
![image](https://github.com/bigcommerce/dev-docs/assets/4650904/bf7ed2aa-bc79-47b2-a266-2d5c44e9a5fa)

**Comment by Tecktron** [comment]
ALSO what kind of bullshit is this:?

500 | Expensive API calls or an internal server error in BigCommerce. | Re-attempt the request three to five times, with increasing delays of at least a minute between attempts.
-- | -- | --
  |   | Try reducing the number of objects being requested. You can request fewer objects in the v2 API, by using ?limit={count}. In v2 and v3 API, fewer objects can be requested by excluding certain fields or only requesting certain fields.

What you should do is hire someone who knows how to build API and properly scale them? Idiots.
No wionder you need to lay people off. Nobody wants to use a SHITTY API like this. 

Tbhat that to you e CTO.

**Comment by chrisboulton** [comment]
Hi @Tecktron,

We value constructive dialogue and are committed to maintaining a professional and respectful community. While we understand that technical issues can be deeply frustrating, we must insist that future communications remain courteous and aligned with our community standards and Code of Conduct.

We apologize for any challenges you've faced with our API and are keen to address them. I’m looking forward to discussing these issues further with you next week on our scheduled call to find a path forward.

Chris,
VP, Infrastructure @ BigCommerce
