### ISSUE TITLE
Feedback for “Logo Image”

### ISSUE THREAD

**Issue by mayrars** [bigcommerce/dev-docs#2105]
I try to change my logo with a URL string but this is not possible, are there any form to change my logo URL with the API?

**Comment by becomevocal** [comment]
@mayrars currently you need to upload the image to set the logo url. 

If you have Postman, you can [import](https://learning.postman.com/docs/getting-started/importing-and-exporting/importing-data/) this collection to make the request easier:

[BigCommerce v3 Store Logo Create.postman_collection.json](https://github.com/bigcommerce/dev-docs/files/13495669/BigCommerce.v3.Store.Logo.Create.postman_collection.json)

This help?

**Comment by slsriehl** [comment]
@mayrars If you need anything further along these lines, please open a new issue at https://github.com/bigcommerce/docs/issues.
