### ISSUE TITLE
Feedback for “Faceted and Textual Search with the GraphQL Storefront API”

### ISSUE THREAD

**Issue by Shmulyitz** [bigcommerce/dev-docs#2107]
Faceted search not pulling up products on graphql storefront api
Here is my query:
`query paginateProducts {
  site {
    search {
      searchProducts(
        filters: {productAttributes: {attribute: "test2", values: ["test 2"]}}
      ) {
        products {
          collectionInfo {
            totalItems
          }
          pageInfo {
            hasNextPage
            startCursor
          }
          edges {
            node {
              id
              name
              sku
            }
          }
        }
        filters(first: 12) {
          edges {
            node {
              ...on PriceSearchFilter {
                name
                selected {
                  minPrice
                  maxPrice
                }
              }
              ... on ProductAttributeSearchFilter {
                displayProductCount
                name
                filterName
                attributes(first: 10) {
                  edges {
                    node {
                      value
                      productCount
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}`

Here is my response:

`{
  "data": {
    "site": {
      "search": {
        "searchProducts": {
          "products": {
            "collectionInfo": {
              "totalItems": 0
            },
            "pageInfo": {
              "hasNextPage": false,
              "startCursor": null
            },
            "edges": []
          },
          "filters": {
            "edges": [
              {
                "node": {
                  "name": "Price",
                  "selected": {
                    "minPrice": null,
                    "maxPrice": null
                  }
                }
              },
              {
                "node": {}
              },
              {
                "node": {
                  "displayProductCount": true,
                  "name": "Test2",
                  "filterName": "test2",
                  "attributes": {
                    "edges": [
                      {
                        "node": {
                          "value": "test 2",
                          "productCount": 1
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}`
As you can see no product was returned however the product count for the attribute is one.

Why is it not pulling up the product?

**Comment by bc-andreadao** [comment]
@Shmulyitz The correct schema for the filters argument would be:
 
`filters: {productAttributes: [{attribute: "test2", values: ["test 2"]}]}`

instead of 

`filters: {productAttributes: {attribute: "test2", values: ["test 2"]}}`

**Comment by Shmulyitz** [comment]
I just tried that and got the same results

**Comment by robincoferbc** [comment]
Hi @Shmulyitz Our search features depend on a search database that indexes records for quicker performance. Occasionally, those indexes may not sync correctly, which can result in search result discrepancies similar to this one. Please start a new support case with our support team, and we can investigate whether that is the cause of this issue. When submitting the new case, please provide any relevant store info and example product IDs that are not appearing in search results, and we can check on that for you. It also may help to reference this Github thread. Thanks!

**Comment by Shmulyitz** [comment]
Thank you, I will do that.

Where do I submit a support case?

**Comment by robincoferbc** [comment]
@Shmulyitz You can access support options within your store's control panel in the Help section in the lower left hand corner. Alternatively, if you are a member of the partner developer program, you can submit a case within the Partner Portal, which will give you direct access to our more advanced support teams.

**Comment by Shmulyitz** [comment]
Thank you!

I"m just wondering can it have anything to do with the fact that this account is an Enterprise trial account?
