### ISSUE TITLE
Feedback for “Orders”

### ISSUE THREAD

**Issue by Joel-Tennant-StockTrim** [bigcommerce/dev-docs#2109]
How do I get which of my Locations an order was dispatched from? 
I see the inventory drop for a location when an order goes through but how do I find which order caused that inventory to drop

**Comment by bc-andreadao** [comment]
@Joel-Tennant-StockTrim If an order was fulfilled with a shipping consignment, you currently cannot retrieve the location from which the order came from. If an order was fulfilled with a pickup consignment, you can retrieve the location from the [Get all Consignments](https://developer.bigcommerce.com/docs/rest-management/orders/order-consignments#get-consignments) endpoint.

**Comment by Joel-Tennant-StockTrim** [comment]
Is it on the roadmap to include the location on an order so we can track the which order came from what location?

**Comment by bc-andreadao** [comment]
As mentioned, you can find which location is included with an order for pickup consignments already. We understand that a dispatch is not traditionally viewed as pickup but more of a shipment, so we are aware we don't fully support an association between locations and dispatch today, but yes, we intend to in the future.
