### ISSUE TITLE
https://developer.bigcommerce.com/ Not Indexed by Google Search

### ISSUE THREAD

**Issue by 34638a** [bigcommerce/dev-docs#2129]
Hi Devs,

This is just a quick issue note that common searches for bigcommerce API documentation of any sort is not resulting in a link to the actual documentation URL https://developer.bigcommerce.com/

I can't seem to find a robots.txt or anything like that to confirm that there is an intentional block on indexing the site but when searching for terms like "Bigcommerce API" or "Bigcommerce App Development" all that comes up is the support form, linking to articles discussing the API.

![image](https://github.com/bigcommerce/dev-docs/assets/8683774/9133571a-b03d-49e9-be73-217894510efa)
![image](https://github.com/bigcommerce/dev-docs/assets/8683774/9e612208-9436-443d-bebb-ca64a4b00aa7)

This is just a advisory to make the issue known as it's surprisingly difficult to find the actual docs without either first going through this github repo or having someone link you directly to it. Given that it's a search result and not a actual issue with the docs code itself, I can't guarantee this is able to be replicated, it may be geo-specific, and google specific. Testing in Duck Duck Go and Bing both return the expected https://developer.bigcommerce.com/ as the top  result.

Cheers for reading and feel free to auto-close as unrelated 🥳

**Comment by slsriehl** [comment]
Hi @34638a -- Many thanks for reporting. The Google-specific indexing issue should be resolved now.

Going forward, you can open issues in https://github.com/bigcommerce/docs.

Thanks for building with BigCommerce!
