### ISSUE TITLE
Can UpdateShipment change the addresses or not?

### ISSUE THREAD

**Issue by IslandUsurper** [bigcommerce/dev-docs#241]
When I try to generate code from `BigCommerce_Orders_API.oas2.json`, I get the following error
> Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 11
Errors: 
        -attribute paths.'/orders/{order_id}/shipments/{shipment_id}'(put).[['unknown']].in is missing
        -attribute responses.OrdersCountResponseCollection.description is missing
Warnings: 
        -attribute paths.'/orders/{order_id}/shipments/{shipment_id}'(put).[['unknown']].in is missing
        -attribute responses.OrdersCountResponseCollection.description is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:470)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:497)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:415)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)

The missing `description` is easy enough to fix, but the missing `in` is interesting. The parameters for that method start off normally: ref to Accept header, ref to Content-Type header, a body with a ref to `createupdateordershipment`. But then there's another schema, that looks like a `createupdateordershipment`, but it also contains `items`, `billing_address`, and `shipping_address` properties, unlike the other one. Interestingly, the example for `createupdateordershipment` includes those three properties, so I don't know what is intended. These two objects look like they should be merged, but someone else should make the call.

**Comment by uwikaiddi** [comment]
Hi @IslandUsurper, thanks for your submission! 
This issue should be resolved now.
