### ISSUE TITLE
Order transaction docs are in bad format, and missing APIs

### ISSUE THREAD

**Issue by yershalom** [bigcommerce/dev-docs#318]
No order transaction get api anymore. Also void and capture are missing.

<img width="295" alt="Screen Shot 2020-02-04 at 19 52 04" src="https://user-images.githubusercontent.com/7933604/73772171-57a86700-4788-11ea-9100-9c7e574bc7c7.png">

The table is badly formatted.
<img width="855" alt="Screen Shot 2020-02-04 at 19 51 46" src="https://user-images.githubusercontent.com/7933604/73772173-57a86700-4788-11ea-9f36-94e6d0aa6176.png">

**Comment by aglensmith** [comment]
Thanks for submitting an issue!

This has been resolved.
