### ISSUE TITLE
restrict_to values in coupons not typed consistently

### ISSUE THREAD

**Issue by annaelizabeth2019** [bigcommerce/dev-docs#354]
When there is nothing in the restricted_to value for the coupons endpoint I get back an empty array, but when there is something I get back an object that contains key "countries" that holds an array of strings. The empty value of restricted_to should be an empty object not an empty array.

**Comment by ektravel** [comment]
Hello @annaelizabeth2019, 
Thank you for bringing this to our attention. Since it is not a documentation-related issue, a ticket has been submitted to BigCommerce's engineering team to address this bug.
