### ISSUE TITLE
Cannot see Widgets locally

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/dev-docs#362]
Recent project required creation of multiple widgets, but was disappointed to see that you can only view them on a live store/theme editor. Is there a way to view this locally during development?

**Comment by mikrdgz** [comment]
Hi there @PeteyRev,

For discussion surrounding workarounds and solutions for working locally with Widgets, we'd suggest bringing the conversation to the [BigCommerce Developer Community](https://jira.bigcommerce.com/browse/DEVDOCS-1880).
