### ISSUE TITLE
I can't create a custom widget through the API

### ISSUE THREAD

**Issue by dulcehc** [bigcommerce/dev-docs#777]
I'm following the [widgets tutorial](https://developer.bigcommerce.com/api-docs/store-management/widgets/tutorial), but although they are displayed in Page builder, the widgets are not working, it doesn't display something in the preview and design views.
<img width="248" alt="Screen Shot 2020-10-15 at 17 26 05" src="https://user-images.githubusercontent.com/19391835/96192374-82e47800-0f0b-11eb-9a35-864a5c572b85.png">

Also, I reviewed other [examples](https://developer.bigcommerce.com/api-docs/store-management/widgets/samples) but I get the same result, the widget is empty.

<img width="959" alt="Screen Shot 2020-10-15 at 17 31 01" src="https://user-images.githubusercontent.com/19391835/96192707-33eb1280-0f0c-11eb-9e9b-b6e552841e64.png">

Here is my code:

widget template
```
{
  "name": "List",
  "template": "<ul>\r\n{{#each list_items}}\r\n <li style=\"color:{{color}};\">{{text}}<\/li>\r\n{{\/each}}\r\n<\/ul>",
  "schema": [
       {
      "type": "tab",
      "label": "Content",
      "sections": []
       }
    ]
}

```
widget

```
{
  "name": "Simple List Test",
  "widget_configuration": {
    "list_items": [
      {
        "color": "blue",
        "text": "The color is blue"
      },
      {
        "color": "green",
        "text": "The color is green"
      },
      {
        "color": "red",
        "text": "The color is red"
      }
    ]
  },
  "widget_template_uuid": "UID TEMPLATE"
}
```

I really appreciate any help you can provide

**Comment by ektravel** [comment]
Hello, @dulcehc. We have updated the [Widgets tutorial](https://developer.bigcommerce.com/api-docs/store-management/widgets/tutorial). Please review [Create a user interface](https://developer.bigcommerce.com/api-docs/store-management/widgets/tutorial#create-a-user-interface) section of the tutorial for instructions on how to create a widget compatible with Page Builder. Thank you!
